<?php

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

$firstNumber = 0;

$secondNumber = 1;

for ($i=0, $sumOfEvenValuedFibonacci = 0; ; $i++) 
{ 
	$fibonacci = $firstNumber + $secondNumber;

	if($fibonacci > 4000000)
	{
		break;
	}
	
	$firstNumber = $secondNumber;

	$secondNumber = $fibonacci;

	if (($fibonacci % 2) == 0)
	{
		$sumOfEvenValuedFibonacci = $sumOfEvenValuedFibonacci + $fibonacci;


	}
}

echo $sumOfEvenValuedFibonacci . PHP_EOL;
